# Generated by Django 5.1.4 on 2025-05-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_question_options_remove_question_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
